# Generated by Django 3.2.5 on 2021-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_questionsetter_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isFile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isMCQ',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='isTrueFalse',
            field=models.BooleanField(default=False),
        ),
    ]
