# Generated by Django 3.2.5 on 2021-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_mcqquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isVerified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
