# Generated by Django 3.2.5 on 2021-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_student_isverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=200)),
                ('elapsedTime', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('group',)},
            },
        ),
    ]
