# Generated by Django 3.2.5 on 2021-12-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_rename_isvarified_questionsetter_isverified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('studentID',)},
        ),
    ]
