# Generated by Django 3.2.5 on 2021-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_student_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupattr',
            name='passcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
