# Generated by Django 3.2.5 on 2021-12-11 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_studentquestionmap_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionmap',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
    ]
