# Generated by Django 3.2 on 2021-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_alter_studentquestionmap_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
