# Generated by Django 3.2 on 2021-12-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_question_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='mark',
            new_name='marks',
        ),
    ]
