# Generated by Django 3.2 on 2021-12-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_filequestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileQuestion',
        ),
    ]
