# Generated by Django 3.2 on 2021-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_delete_filequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupattr',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
